[project]
name = "audio-only"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4",
    "bs4",
    "docopt",
    "feedgen",
    "lxml",
    "pip-chill",
    "python-dateutil",
    "six",
    "soupsieve",
]
